### ISSUE TITLE
error linking library

### ISSUE THREAD

**Issue by veethahavya-CU-cz** [mmasciol/yaml-fortran#8]
first off - thanks for writing the wrapper!

i was able to compile the source code and produce the modules and libraries (also shared) successfully. the pre-compiled test program works too.

it was a bit unclear to me as to what resources to link to compile my own test program, but after `ldd`-ing the pre-compiled test executables, if i understand right, i need to link _libyaml-wrapper.so_ and _libyaml-cpp.so.0.7_ to compile my program in addition to including the path to the _.mod files_.

I tried doing this via: ` gfortran -I./build/src/yaml-fortran/  -L./bin/ -lyaml-wrapper -lyaml-cpp mytest.f90 -o mytest`
but this leaves me with the following error message:
```
/usr/bin/ld: /tmp/ccieJX3p.o: warning: relocation against `__yamlread_MOD___vtab_yamlread_Yamlmap' in read-only section `.text'
/usr/bin/ld: /tmp/ccieJX3p.o: in function `MAIN__':
test_yaml.f90:(.text+0x178): undefined reference to `__yamlread_MOD_yaml_open_file'
/usr/bin/ld: test_yaml.f90:(.text+0x227): undefined reference to `__yamlread_MOD_yaml_start_from_map'
/usr/bin/ld: test_yaml.f90:(.text+0x366): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0x420): undefined reference to `__yamlread_MOD_map_value_map'
/usr/bin/ld: test_yaml.f90:(.text+0x55f): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0x619): undefined reference to `__yamlread_MOD_map_value_map'
/usr/bin/ld: test_yaml.f90:(.text+0x7ae): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0x839): undefined reference to `__yamlread_MOD_map_value_str'
/usr/bin/ld: test_yaml.f90:(.text+0x8f7): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0x989): undefined reference to `__yamlread_MOD_map_value_double_1d'
/usr/bin/ld: test_yaml.f90:(.text+0xa57): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0xae9): undefined reference to `__yamlread_MOD_map_value_integer_2d'
/usr/bin/ld: test_yaml.f90:(.text+0xc4c): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0xce0): undefined reference to `__yamlread_MOD_map_value_str'
/usr/bin/ld: test_yaml.f90:(.text+0xd9e): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0xe30): undefined reference to `__yamlread_MOD_map_value_double_1d'
/usr/bin/ld: test_yaml.f90:(.text+0xefe): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0xf90): undefined reference to `__yamlread_MOD_map_value_double_2d'
/usr/bin/ld: test_yaml.f90:(.text+0x1233): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0x1257): undefined reference to `__yamlread_MOD_map_destroy'
/usr/bin/ld: test_yaml.f90:(.text+0x1452): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0x1476): undefined reference to `__yamlread_MOD_map_destroy'
/usr/bin/ld: test_yaml.f90:(.text+0x147d): undefined reference to `__yamlread_MOD___vtab_yamlread_Yamlmap'
/usr/bin/ld: test_yaml.f90:(.text+0x14a1): undefined reference to `__yamlread_MOD_map_destroy'
/usr/bin/ld: test_yaml.f90:(.text+0x14ad): undefined reference to `__yamlread_MOD_yaml_close_file'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```

any help is highly appreciated!

**Comment by mmasciol** [comment]
Hi,

Happy to help and sorry about the trouble you've encountered.

Does your source file include the 

use YAMLInterface 
use YAMLRead

statements in it? Those files should be bundled in the project getting built.

**Comment by veethahavya-CU-cz** [comment]
thanks for offering to help.

yes, it does include those statements. i am basically trying to compile an example (TestMap) you have included, myself, to get started.

unfortunately, I have not prepared a makefile for the compilation (as i do not know my way around them well), and i am just using bash commands.

firstly, i made a copy of the example with very few modifications and placed it in the root directory as "mytest.f90" (attached, in tarball). basically this is the program i am trying to compile.

and then i am compiling the program with the following commands:
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/_path_/_until_/_project_root_/yaml-fortran/bin
$ gfortran -I./build/src/yaml-fortran/ -L./bin -lyaml-wrapper -lyaml-cpp  mytest.f90 -o mytest


[test.tar.gz](https://github.com/mmasciol/yaml-fortran/files/10031714/test.tar.gz)

**Comment by mmasciol** [comment]
It's because the `yaml-interface.f90`, `yaml-read.f90` need to be compiled and a 3rd library is missing in the link stage. I was able to build the `test.f90` with this makefile. You will need to adjust the final line so that it points to the correct library files location inside of bin. 

```
FC     = gfortran 
FFLAGS = -O1 -g 
SRC    = yaml-interface.f90 yaml-read.f90 mytest.f90

OBJ = ${SRC:.f90=.o} 

%.o: %.f90 
	$(FC) $(FFLAGS) -o $@ -c $<

test: $(OBJ)
	$(FC) $(FFLAGS) -o $@ $(OBJ) -Wl,-rpath,/home/local/fortran/bin ../../bin/libyaml-interface.a ../../bin/libyaml-wrapper.so ../../bin/libyaml-cpp.so.0.7.0 
```

**Comment by veethahavya-CU-cz** [comment]
worked alright. thanks for the help!

may i suggest that the objects be compiled as static/dynamic libraries and installed (perhaps in the standard /usr/local dir or provided --prefix) for ease-of-use for the end user?

unfortunately, i am not good with makefiles, but it would be something like this in bash:

```
cd ./src/yaml-fortran
gfortran -c -fPIC yaml-interface.f90 -o yaml-interface.o
gfortran -c -fPIC yaml-read.f90 -o yaml-read.o
gfortran -shared yaml-interface.o yaml-read.o -o libyamlf.so OR ar cr libyamlfort.a yaml-interface.o yaml-read.o
cp libyamlf.so ../../bin/ OR cp libyamlfort.a ../../bin/
mkdir -p /usr/local/lib/yaml-fortran && cp *.so *.a /usr/local/lib/yaml-fortran
mkdir -p /usr/local/inclide/yaml-fortran && cp *.mod /usr/local/inclide/yaml-fortran
```

that way, the end used could just link against the library so:
```
(FC) (FCFLAGS) -I/usr/local/inclide/yaml-fortran -L/usr/local/lib/yaml-fortran -lyaml-cpp -lyaml-wrapper -lyamlf (OR -lyaml-fortran)
```
